src/Entity/AdminUser.php
<?php

namespace App\Entity;

use App\Repository\AdminUserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: AdminUserRepository::class)]
class AdminUser implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $login = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\OneToMany(mappedBy: 'user_login', targetEntity: AdminLog::class)]
    private Collection $logs;

    #[ORM\OneToMany(mappedBy: 'user_login', targetEntity: AdminAccessLog::class)]
    private Collection $accesslogs;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: true)]
    private ?AdminUserRole $role = null;

    #[ORM\ManyToMany(targetEntity: BlogArticle::class, mappedBy: 'users')]
    private Collection $blogArticles;

    #[ORM\OneToOne(cascade: ['persist'])]
    private ?AdminLog $_created = null;

    #[ORM\OneToOne(cascade: ['persist'])]
    private ?AdminLog $_updated = null;

    public function __construct()
    {
        $this->logs = new ArrayCollection();
        $this->accesslogs = new ArrayCollection();
        $this->blogArticles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }
    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): static
    {
        $this->login = $login;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection<int, AdminLog>
     */
    public function getLogs(): Collection
    {
        return $this->logs;
    }

    public function addLog(AdminLog $log): static
    {
        if (!$this->logs->contains($log)) {
            $this->logs->add($log);
            $log->setUserLogin($this);
        }

        return $this;
    }

    public function removeLog(AdminLog $log): static
    {
        if ($this->logs->removeElement($log)) {
            // set the owning side to null (unless already changed)
            if ($log->getUserLogin() === $this) {
                $log->setUserLogin(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, AdminAccessLog>
     */
    public function getAccesslogs(): Collection
    {
        return $this->accesslogs;
    }

    public function addAccesslog(AdminAccessLog $accesslog): static
    {
        if (!$this->accesslogs->contains($accesslog)) {
            $this->accesslogs->add($accesslog);
        }

        return $this;
    }

    public function removeAccesslog(AdminAccessLog $accesslog): static
    {
        if ($this->accesslogs->removeElement($accesslog)) {
        }

        return $this;
    }

    /**
     * @return Collection<int, BlogArticle>
     */
    public function getBlogArticles(): Collection
    {
        return $this->blogArticles;
    }

    public function addBlogArticle(BlogArticle $blogArticle): static
    {
        if (!$this->blogArticles->contains($blogArticle)) {
            $this->blogArticles->add($blogArticle);
            $blogArticle->addUser($this);
        }

        return $this;
    }

    public function removeBlogArticle(BlogArticle $blogArticle): static
    {
        if ($this->blogArticles->removeElement($blogArticle)) {
            $blogArticle->removeUser($this);
        }

        return $this;
    }

    public function getRole(): ?AdminUserRole
    {
        return $this->role;
    }

    public function setRole(?AdminUserRole $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function __toString(): string
    {
        return $this->login.' - '.$this->role;
    }


    public function getCreated(): ?AdminLog
    {
        return $this->_created;
    }

    public function setCreated(?AdminLog $_created): static
    {
        $this->_created = $_created;

        return $this;
    }

    public function getUpdated(): ?AdminLog
    {
        return $this->_updated;
    }

    public function setUpdated(?AdminLog $_updated): static
    {
        $this->_updated = $_updated;

        return $this;
    }

    // User interface

    public function getRoles(): array
    {
        return array($this->role->getCode());
    }

    public function getUserIdentifier(): string
    {
        return $this->login;
    }
    public function eraseCredentials(): void
    {

    }
    public function getSalt():?string 
    {
        return null;
    }
}

src/Entity/Tag.php
<?php

namespace App\Entity;

use App\Repository\TagRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TagRepository::class)]
class Tag
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $lib = null;

    #[ORM\ManyToMany(targetEntity: Projet::class, mappedBy: 'tags')]
    private Collection $projets;

    #[ORM\ManyToMany(targetEntity: BlogArticle::class, mappedBy: 'tags')]
    private Collection $blogArticles;

    #[ORM\OneToOne(cascade: ['persist'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?AdminLog $_created = null;

    #[ORM\OneToOne(cascade: ['persist'])]
    private ?AdminLog $_updated = null;

    public function __construct()
    {
        $this->projets = new ArrayCollection();
        $this->blogArticles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getLib(): ?string
    {
        return $this->lib;
    }

    public function setLib(string $lib): static
    {
        $this->lib = $lib;

        return $this;
    }

    /**
     * @return Collection<int, Projet>
     */
    public function getProjets(): Collection
    {
        return $this->projets;
    }

    public function addProjet(Projet $projet): static
    {
        if (!$this->projets->contains($projet)) {
            $this->projets->add($projet);
            $projet->addTag($this);
        }

        return $this;
    }

    public function removeProjet(Projet $projet): static
    {
        if ($this->projets->removeElement($projet)) {
            $projet->removeTag($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, BlogArticle>
     */
    public function getBlogArticles(): Collection
    {
        return $this->blogArticles;
    }

    public function addBlogArticle(BlogArticle $blogArticle): static
    {
        if (!$this->blogArticles->contains($blogArticle)) {
            $this->blogArticles->add($blogArticle);
            $blogArticle->addTag($this);
        }

        return $this;
    }

    public function removeBlogArticle(BlogArticle $blogArticle): static
    {
        if ($this->blogArticles->removeElement($blogArticle)) {
            $blogArticle->removeTag($this);
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->lib;
    }

    public function getCreated(): ?AdminLog
    {
        return $this->_created;
    }

    public function setCreated(AdminLog $_created): static
    {
        $this->_created = $_created;

        return $this;
    }

    public function getUpdated(): ?AdminLog
    {
        return $this->_updated;
    }

    public function setUpdated(?AdminLog $_updated): static
    {
        $this->_updated = $_updated;

        return $this;
    }
}

templates/blog-base.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{asset('css/blog.css')}}">
<link rel="stylesheet" href="{{asset('css/component/tags.css')}}">
<link rel="stylesheet" href="{{asset('css/component/form.css')}}">
{% endblock %}

{% block body %}
<section class="-flex-sb">
    <div class="left">
        <div>
            <h2 class="-cl-orange">Tous les thèmes :</h2>
            <ul class="-cl-brown -fs-18">
            {% for t in themes %}
                <li><a class="-cl-brown" href="{{path('blog-theme', {"theme": t.lib }) }}">{{ t.lib }}</a></li>
            {% endfor %}
            </ul>
        </div>

        <div>
            <h2 class="-cl-orange">Tous les tags :</h2>
            <div class="-cl-brown -fs-18">
            <span>-</span>
            {% for t in tags %}
                <span class="-cl-brown -tdu"><a class="-cl-brown" href="{{path('blog-tag', {"tag": t.lib }) }}">#{{ t.lib }}</a></span>
                 - 
            {% endfor %}
            </div>
        </div>

        <div>
            <h2 class="-cl-orange">Par date :</h2>
            <ul class="-cl-brown -fs-18">
            {% for d in dates %}
                <li class="-cl-brown"><a class="-cl-brown" href="{{path('blog-date', {"date": d | date("Y-m")}) }}">{{ d | date("F Y") }}</a></li> 
            {% endfor %}
            </ul>
        </div>
    </div>

    {% block right %}
    {% endblock %}
</section>
{% endblock %}

templates/blog.html.twig
{% extends 'blog-base.html.twig' %}

{% block right %}
<div class="right">
    <h1><span class="-cl-blue">Ici, on papote</span><span class="-cl-orange"> web et informatique</span></h1>
    <p class="-cl-brown">{{filter}}</p>
    {% for a in articles %}
    <div class="article -flex-fs">
        <img src="{{ vich_uploader_asset(a, 'imageFile') | imagine_filter('blog_article_tn') }}" alt="{{ a.imageName }}">
        <div>
            <h2 class="-cl-blue">{{ a.titre }}</h1>
            <p class="-str -it -cl-brown">Posté par {{ a.created.userlogin.login}} | {{ a.date | date("d/m/Y") }} | {{a.theme.lib}}</p>
            <br>
            <div class="-cl-brown">{{ a.contenu|striptags|u.truncate(250,'...',false)|raw }}</div>
            <br>
            <span>-</span>
            {% for t in a.tags %}
                <span class="-cl-brown -tdu">{{ t.lib }}</span>
                 - 
            {% endfor %}
            <br><br>
            <button class="-white-outline -btn-orange -btn-big -font-lb"><a href="{{path('blog-article', {"slug": a.titreslug}) }}">Lire la suite</a></button>
        </div>
    </div>
    {% endfor %}
    <div class="article -flex-sb">
        {% if page > 1 %}
        <a class="-cl-brown -str" href="{{path(route, {'date': date, 'tag': tag, 'theme': theme, 'page': page - 1}) }}">Page précédente</a>
        {% endif %}

        <div></div> {# Div vide pour l'alignement de 'page suivante' => ne pas supprimer #}

        {% if page != lastpage %}
        <a class="-cl-brown -str" href="{{path(route, {'date': date, 'tag': tag, 'theme': theme, 'page': page + 1}) }}">Page Suivante</a>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/competence-detail.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{asset('css/competence-detail.css')}}">
{% endblock %}

{% block body %}
<section class="-flex-sb">
    <div class="left -flex-btm">
        <img src={{asset('img/ordinateur.png')}}>
        <h2 class="-cl-orange -tac -fs-32">Vous avez un projet ?</h2>
        <button class="-btn-blue -btn-big -font-lb">Demande de devis gratuit</button>
    </div>
    <div class="right">
        <h1 class="-cl-orange">{{ c.titre }}</h1>
        <div class="contenu">{{ c.contenu | raw }}</div>
    </div>
</section>
{% endblock %}

templates/confidentialite.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{% endblock %}

templates/hiring.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{asset('css/home.css')}}">
<link rel="stylesheet" href="{{asset('css/hiring.css')}}">
{% endblock %}

{% block body %}
<h2 class="-cl-orange">Nous recrutons!</h2>
<div class="jobs">
    {% for j in jobs %}
    <div class="component-job">
        <p>{{j.lib}}</p>
        {% if j.open %}
            <p style='color:green;'>Ouvert</p>
        {% else %}
            <p style='color:red;'>Fermé</p>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/infogerance.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{% endblock %}

templates/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
<form method="post">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {# {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %} #}

    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputEmail">Email</label>
    <input type="text" value="{{ last_username }}" name="_username" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
    <label for="inputPassword">Password</label>
    <input type="password" name="_password" id="inputPassword" class="form-control" autocomplete="current-password" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    {#
        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
    #}

    <button class="btn btn-lg btn-primary" type="submit">
        Sign in
    </button>
</form>
{% endblock %}

templates/maintenance.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{% endblock %}

templates/miw-informatique.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{% endblock %}

templates/miw-magasin.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{% endblock %}

templates/miw-telecom.html.twig
{% extends 'base.html.twig' %}

{% block body %}
{% endblock %}

templates/partners.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{asset('css/partners.css')}}">
<link rel="stylesheet" href="{{asset('css/component/partenaire.css')}}">
{% endblock %}

{% block body %}
    <h2 class="-cl-orange">Nos partenaires</h2>
    <p class="-cl-brown">Retrouvez ici certains de nos partenaires.</p>
    <div class="partners">
        {% for p in partners %}
        <div class="component-job">
            <img class= "partner-img" src="{{ vich_uploader_asset(p, 'imageFile') | imagine_filter('partner') }}" alt="{{ p.imageName }}"">
        </div>
        {% endfor %}
    </div>
{% endblock %}

templates/project-detail.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{asset('css/project-detail.css')}}">
<link rel="stylesheet" href="{{asset('css/component/tags.css')}}">
<link rel="stylesheet" href="{{asset('bundles-extra/splide-4.1.3/themes/splide-skyblue.min.css')}}">
{% endblock %}

{% block javascripts %}
<script src="{{asset('bundles-extra/splide-4.1.3/splide.min.js')}}"></script>
<script>
  document.addEventListener( 'DOMContentLoaded', function() {
    var splide = new Splide( '.splide', {
        type: 'loop',
    });
    splide.mount();
  } );
</script>

{% endblock %}

{% block body %}

<div class="projet">
    <div class="projecttext -tac">
        <h1 class="-cl-orange">{{p.titre}}</h1>
        <h2 class="-cl-blue">{{p.soustitre}}</h1>
    </div>

    <div class="flex -flex-ce">

        <div class="flexleft">
            <section class="splide" aria-label="Splide Basic HTML Example">
                <div class="splide__track">
                    <div class="splide__list">

                        {% for i in p.images %}
                        <div class="splide__slide">
                            <img src="{{ vich_uploader_asset(i, 'imageFile') | imagine_filter('project') }}" alt="{{ i.imageName }}">
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </section>
        </div>

        <div class="flexright">
            <div class="-cl-brown">{{p.description | raw}}</div>
            <div>
                {% for t in p.tags %}
                <span class="tag">{{t.lib}}</span>
                {% endfor %}
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/projects.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="{{asset('css/projects.css')}}">
{% endblock %}

{% block body %}

<div class="projectsmenu -flex-ce">
        {% if page > 1 %}
        <a href="{{path('projets-page', {'type': type, 'page': page - 1}) }}">
            <i class="fa-solid fa-chevron-left -cl-black -fs-24"></i>
        </a>
        <div class="-flex-btm"><h2 class="-fs-20 -cl-brown">{{ page - 1 }}</h2></div>
        {% else %}
        <a>
            <i class="fa-solid fa-chevron-left -cl-black -fs-24 -invis"></i>
        </a>
        <div class="-flex-btm"><h2 class="-fs-20 -cl-brown -invis">{{ page - 1 }}</h2></div>
        {% endif %}

        <h1 class="-fs-24">{{ page }}</h1>

        {% if page != lastpage %}
        <div class="-flex-btm"><h2 class="-fs-20 -cl-brown">{{ page + 1 }}</h2></div>
        <a href="{{path('projets-page', {'type': type, 'page': page + 1}) }}">
            <i class="fa-solid fa-chevron-right -cl-black -fs-24"></i>
        </a>
        {% else %}
        <div class="-flex-btm"><h2 class="-fs-20 -cl-brown -invis">{{ page + 1 }}</h2></div>
        <a>
            <i class="fa-solid fa-chevron-right -cl-black -fs-24 -invis"></i>
        </a>
        {% endif %}
    </div>

<div class="projects -flex-ce">
    {% for p in projects %}
    {% set i = p.images[0] %}
    <div class="project">
        <a href="{{ path('projet-detail', {"type":type, "slug":p.titreslug }) }}">
            <img src="{{ vich_uploader_asset(i, 'imageFile') | imagine_filter('project_tn') }}" alt="{{ i.imageName }}">
        </a>
        <div class="projecttext">
            <h1 class="-cl-orange">{{p.titre}}</h1>
            <h2 class="-cl-blue">{{p.soustitre}}</h1>
            <div class="-cl-brown">{{p.descriptioncourte | raw}}</div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}